### ISSUE TITLE
Akka: Implications of the streaming nature of Request/Response Entities

### ISSUE THREAD

**Issue by NicolasRouquette** [Jarlakxen/drunk#3]
As of [v2.3.0 AkkaHttpBackend.send()](https://github.com/Jarlakxen/drunk/blob/v2.3.0/src/main/scala/com/github/jarlakxen/drunk/backend/AkkaHttpBackend.scala#L77) does not conform with the Akka doc, specifically: https://doc.akka.io/docs/akka-http/current/implications-of-streaming-http-entity.html#discarding-the-http-response-entity-client-, because it does not call `discardEntityBytes()`.

**Comment by NicolasRouquette** [comment]
To avoid problems with `akka.stream.AbruptTerminationException`, I added an alternative backend based on Akka Http Flow Connection (see: https://github.com/akka/akka-http/issues/497#issue-188074838)

**Comment by Jarlakxen** [comment]
Oh! Nice!
Thanks for tackle this issues =)
I'm going to review the PR

**Comment by NicolasRouquette** [comment]
Great!
